### ISSUE TITLE
"set" array support

### ISSUE THREAD

**Issue by jayvdb** [gnprice/toml-cli#10]
As noted on the README, it isnt possible to set a key to be an array value, i.e. `foo = ["bar"]`

**Comment by gnprice** [comment]
#16 is a related issue, for setting ints and bools (as well as the existing strings.)

**Comment by gnprice** [comment]
Thanks @jayvdb for filing this!

I think the main question for how this should work is what the command-line interface for it should look like.

Do you have a context where you'd like to use `toml set` to set an array value? A concrete use case would be a helpful ingredient for thinking through the interface.

As illustrated [in the TOML spec](https://toml.io/en/v1.0.0#array), a TOML array can contain a wide variety of types of values, and can mix types:
```toml
nested_mixed_array = [ [ 1, 2 ], ["a", "b", "c"] ]
mixed_floats_and_ints = [ 0.1, 0.2, 0.5, 1, 2, 5 ]
contributors = [
  "Foo Bar <foo@example.com>",
  { name = "Baz Qux", email = "bazqux@example.com", url = "https://example.com/bazqux" }
]
```

So ideally the interface here would both:
* make setting arbitrary arrays possible;
* make setting common kinds of arrays easy, and amenable to nice clean code.

Gauging the second part of that requires a guess as to what's common, which is where seeing a concrete use case comes in.
